# Sample file for running tests with Travis CI.
#
# NOTE: you will need to copy this file to your plugin root!
#
# Doing a `ln --symbolic ci/.travis.yml` won't work as Travis expects
# to read the *.travis.yml* file BEFORE it initializes git submodules.
#
---
sudo: required
language: minimal
matrix:
  include:
  - env: ELASTIC_STACK_VERSION=5.x
  - env: ELASTIC_STACK_VERSION=6.x
  - env: ELASTIC_STACK_VERSION=7.x
  - env: ELASTIC_STACK_VERSION=7.x SNAPSHOT=true
  - env: ELASTIC_STACK_VERSION=8.x SNAPSHOT=true
  - env: ELASTIC_STACK_VERSION=7.x
    install: ci/performance/docker-setup.sh
    script: ci/performance/docker-run.sh
  - env: ELASTIC_STACK_VERSION=8.x SNAPSHOT=true
    install: ci/performance/docker-setup.sh
    script: ci/performance/docker-run.sh
  fast_finish: true
#allow_failures:
#  - env: ELASTIC_STACK_VERSION=8.x SNAPSHOT=true
#  - env: ELASTIC_STACK_VERSION=7.x SNAPSHOT=true
install: ci/unit/docker-setup.sh
script: ci/unit/docker-run.sh
