import:
- logstash-plugins/.ci:travis/defaults.yml@1.x
- logstash-plugins/.ci:travis/exec.yml@1.x
- logstash-plugins/.ci:travis/matrix.yml@1.x

env:
  global:
  - HAS_PERFORMANCE_TESTS=1

allow_failures:
  - name: Performance
    if: type = cron
