version: '3'

# run tests:  cd ci/performance; docker-compose up --build --force-recreate
# manual:  cd ci/performance; docker-compose run logstash bash
services:

  logstash:
    build:
      context: ../../
      dockerfile: ci/performance/Dockerfile
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - DISTRIBUTION=${DISTRIBUTION:-default}
        - INTEGRATION=false
    command: jruby -rbundler/setup -S rspec -fd --tag performance
    env_file: docker.env
    environment:
      - SPEC_OPTS
    tty: true
